# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c621ababb50c19462210f44bfd27cffa8e5ebfe77f19a6dda66bb49e7ca0a4bd6434b11e086a658097e2fbb42a4b9cf5d7d4abdf49acb0f9ef266639d08ac43c

test:
  secret_key_base: 9471ad995b724cba42f4e4fdaa05aceec9eada8bf9252b0902b87ae88c9d8f24b97d7292d3f38188ec933b5826897f1b7335f3df0018c746e5dab0c6d287ffe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
